dependencies:
- name: ecs-monitoring
  version: 3.7.0-1093.ae5ea5e2 # no_auto_change__monitoring_auto_change
  condition: global.monitoring.enabled
  repository: https://asdrepo.isus.emc.com/artifactory/objectscale-helm-build/
- name: rsyslog-client
  repository: https://asdrepo.isus.emc.com/artifactory/objectscale-helm-build/
  version: 3.7.0-1093.ae5ea5e2xx # no_auto_change__monitoring_auto_change
