---
apiVersion: v1
appVersion: 0.4.0
description: A Helm chart for sonobuoy
name: sonobuoy
version: 0.4.0
icon: https://avatars0.githubusercontent.com/u/12926680
maintainers:
- name: Heptio
  url: https://heptio.com/
