---
# Default values for service-pod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# These global settings relate to service-pod
global:
  # Name of a Kubernetes secret with Docker credentials for the private registry
  # registrySecret: dockerhub-registry-secret

  # The private docker registry hosting containers
  # registry: harbor.lss.emc.com/ecs
  registry: emccorp

# The default docker tag and pull policy for service-pod
tag: 2.0.61
pullPolicy: IfNotPresent
# product for which the service pod is required
# product: objectscale

# The image configured for the service-pod
image:
  repository: base-service-tools
  # tag: stable
  # pullPolicy: IfNotPresent

sshCred:
  user: "root"
  group: "adm"
  password: "ChangeMe"

# specify the requests and limits for the pod
resources:
  requests:
    memory: 1Gi
    storage: 10Gi
  limits:
    storage: 20Gi
