---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "srs-gateway.notifierServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.DockerSecret }}
imagePullSecrets:
  - name: {{ .Values.DockerSecret }}
{{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "srs-gateway.notifierServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ecs.dellemc.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - decks.ecs.dellemc.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - kahm.emcecs.github.com
  resources:
  - notifiers
  verbs:
  - "*"
- apiGroups:
  - app.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  - extensions
  resources:
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "srs-gateway.notifierServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "srs-gateway.notifierServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "srs-gateway.notifierServiceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
