---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: influxdbs.influxdata.com
  labels:
    app.kubernetes.io/name: objectscale-manager
    helm.sh/chart: objectscale-manager
    app.kubernetes.io/component: ecs-flex-influx
    app.kubernetes.io/part-of: objectscale-manager
    app.kubernetes.io/managed-by: nautilus
spec:
  group: influxdata.com
  names:
    kind: Influxdb
    listKind: InfluxdbList
    plural: influxdbs
    singular: influxdb
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.influxdata.com
  labels:
    app.kubernetes.io/name: objectscale-manager
    helm.sh/chart: objectscale-manager
    app.kubernetes.io/component: ecs-flex-influx
    app.kubernetes.io/part-of: objectscale-manager
    app.kubernetes.io/managed-by: nautilus
spec:
  group: influxdata.com
  names:
    kind: Backup
    listKind: BackupList
    plural: backups
    singular: backup
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restores.influxdata.com
  labels:
    app.kubernetes.io/name: objectscale-manager
    helm.sh/chart: objectscale-manager
    app.kubernetes.io/component: ecs-flex-influx
    app.kubernetes.io/part-of: objectscale-manager
    app.kubernetes.io/managed-by: nautilus
spec:
  group: influxdata.com
  names:
    kind: Restore
    listKind: RestoreList
    plural: restores
    singular: restore
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
