{{- if eq .Values.installObjectStoreCRD true }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ecsclusters.ecs.dellemc.com
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: ecs.dellemc.com
  names:
    kind: ECSCluster
    listKind: ECSClusterList
    plural: ecsclusters
    singular: ecscluster
    shortNames:
    - ecs
    - ecs-cluster
  scope: Namespaced
  version: v1beta1
  additionalPrinterColumns:
  - name: PHASE
    type: string
    description: The current phase of cluster operation
    JSONPath: .status.phase
  - name: READY COMPONENTS
    type: string
    description: A string display of the number of components ready
    JSONPath: .status.readyComponents
  - name: S3 ENDPOINT
    type: string
    description: The HTTPS endpoint for accessing the cluster via S3
    JSONPath: .status.endpoints.s3Secure
  - name: MGMT API
    type: string
    description: The HTTPS location for the management API
    JSONPath: .status.endpoints.managementAPI
{{- end }}
