---
apiVersion: rbac.authorization.k8s.io/v1
{{- if eq .Values.global.watchNamespace "" }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
metadata:
  creationTimestamp: null
  name: objectscale-influxdb-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: ecs-flex-influx
    app.kubernetes.io/part-of: objectscale-manager
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - pods/attach
      - pods/exec
      - namespaces
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - influxdata.com
    resources:
      - '*'
      - backups
      - restores
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: objectscale-influxdb-operator
  namespace: {{ .Release.Namespace }}
---
{{- if eq .Values.global.watchNamespace "" }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectscale-influxdb-operator
subjects:
  - kind: ServiceAccount
    name: objectscale-influxdb-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  {{- if eq .Values.global.watchNamespace "" }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: objectscale-influxdb-operator
  apiGroup: rbac.authorization.k8s.io
