---
apiVersion: v1
appVersion: 1.0.2-17
description: A Helm chart for Dell EMC SRS Gateway Custom Resource Support
name: srs-gateway
version: 0.19.1
icon: https://avatars0.githubusercontent.com/u/12926680
maintainers:
- name: Dell EMC
  url: http://dellemc.com
