---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: |-
    {{ .Release.Name }}-fio-test-volume
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
