apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atlas-operator-binding
  labels:
{{ include "atlas-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: atlas-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
