apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.global.watchAllNamespaces | ternary "ClusterRoleBinding" "RoleBinding" }}
metadata:
  name: atlas-operator-binding
{{- if ne .Values.global.watchAllNamespaces true }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
{{ include "atlas-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.global.watchAllNamespaces | ternary "ClusterRole" "Role" }}
  name: atlas-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
