---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectscale-graphql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-graphql
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: objectscale-manager
      app.kubernetes.io/component: objectscale-graphql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: objectscale-manager
        app.kubernetes.io/component: objectscale-graphql
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name}}
        operator: objectscale-operator
        product: objectscale
    spec:
      serviceAccountName: objectscale-api
      containers:
        - name: objectscale-graphql
          image: {{ .Values.global.registry }}/{{ .Values.graphql.image.repository }}:{{ default .Values.tag .Values.graphql.image.tag }}
          imagePullPolicy: {{ default .Values.pullPolicy .Values.graphql.image.pullPolicy }}
          env:
            - name: OBJSTORE_AVAILABLE_VERSIONS
              value: {{ .Values.objectStoreAvailableVersions | toJson | quote }}
            - name: GRAPHQL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GLOBAL_REGISTRY
              value: {{ .Values.global.registry }}
            - name: LICENSE_CHART_VERSION
              value: {{ default "1.1.0" .Values.decks.licenseChartVersion }}
            - name: SRSGATEWAY_CHART_VERSION
              value: {{ default "1.1.0" .Values.decks.srsGatewayChartVersion }}
            - name: OPERATOR_NAME
              value: objectscale-operator
            - name: LOG_DIRECTION
{{- if .Values.logReceiver.type }}
              value: file
{{- else }}
              value: stdout
{{- end }}
{{- if .Values.graphql.withPlayground }}
          args:
            - "-P"
{{- end }}
{{- if or .Values.logReceiver.type .Values.logReceiver.create }}
        - name: fluentbit-agent
          image: {{ .Values.global.registry }}/{{ .Values.fluentbitAgent.image.repository }}:{{ default .Values.tag .Values.fluentbitAgent.image.tag }}
          imagePullPolicy: {{ default .Values.pullPolicy .Values.fluentbitAgent.image.pullPolicy }}
          env:
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
          - name: log
            readOnly: true
            mountPath: /var/log
          - name: config
            mountPath: /fluent-bit/etc

      volumes:
        - name: log
          emptyDir: {}
        - name: config
          configMap:
            name: {{ .Release.Name }}-manager-logs-config
{{- end }}
