---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: objectscale-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-operator
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
{{- if .Values.global.registrySecret }}
imagePullSecrets:
  - name: {{ .Values.global.registrySecret }}
{{- end }}
---
{{- if eq .Values.global.watchAllNamespaces true }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-objectscale-operator
{{- if ne .Values.global.watchAllNamespaces true }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-operator
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - ecs.dellemc.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - decks.ecs.dellemc.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - app.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - atlas.dellemc.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - bookkeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - pravega.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - influxdata.com
  resources:
  - influxdbs
  verbs:
  - "*"
- apiGroups:
  - cns.vmware.com
  resources:
  - "*"
  verbs:
  - "*"
---
{{- if eq .Values.global.watchAllNamespaces true }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-objectscale-operator
{{- if ne .Values.global.watchAllNamespaces true }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-operator
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
subjects:
- kind: ServiceAccount
  name: objectscale-operator
  namespace: {{ .Release.Namespace }}
roleRef:
{{- if eq .Values.global.watchAllNamespaces true }}
  kind: ClusterRole
{{- else }}
  kind: Role
{{- end }}
  name: {{ .Release.Namespace }}-objectscale-operator
  apiGroup: rbac.authorization.k8s.io
