{{- if or (eq .Values.global.platform "VMware") (eq .Values.global.platform "VMware-PKS") }}
---
apiVersion: v1
kind: Service
metadata:
  name: objectscale-vsphere-plugin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-vsphere-plugin
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
spec:
  type: {{ .Values.vSpherePlugin.service.type }}
  selector:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/component: objectscale-vsphere-plugin
  ports: {{ toYaml .Values.vSpherePlugin.service.ports | nindent 6 }}
{{- end }}
