{{- if or (eq .Values.global.platform "VMware") (eq .Values.global.platform "VMware-PKS") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectscale-vsphere-plugin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-vsphere-plugin
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: objectscale-manager
      app.kubernetes.io/component: objectscale-vsphere-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: objectscale-manager
        app.kubernetes.io/component: objectscale-vsphere-plugin
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name}}
        operator: objectscale-operator
        product: objectscale
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: objectscale-vsphere-plugin
  {{- if (eq .Values.global.platform "VMware") }}
        - name: certificate
          secret:
            secretName: flex-plugin-secret
  {{- end }}
      containers:
        - name: objectscale-vsphere-plugin
          image: {{ .Values.global.registry }}/{{ .Values.vSpherePlugin.image.repository }}:{{ default .Values.tag .Values.vSpherePlugin.image.tag }}
          env:
            - name: OPERATOR_NAME
              value: objectscale-operator
          imagePullPolicy: {{ default .Values.pullPolicy .Values.vSpherePlugin.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /conf/upstream.conf
              subPath: upstream.conf
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
  {{- if (eq .Values.global.platform "VMware") }}
            - name: certificate
              mountPath: /etc/nginx/ssl
  {{- end }}
{{- end }}
