---
{{- if .Values.createdecksappResource}}
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "decks"
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: "decks"
    app.kubernetes.io/version: {{.Values.tag}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: nautilus
    helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
    release: {{.Release.Name}}
  annotations:
    com.dellemc.kahm.subscribed: "true"
    nautilus.dellemc.com/chart-version: {{ .Chart.Version }}
    nautilus.dellemc.com/chart-values: {{ .Values | toJson | quote }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "decks"
  componentKinds:
    - group: apps
      kind: Deployment
    - group: core
      kind: ConfigMap
    - group: core
      kind: ServiceAccount
    - group: core
      kind: Pod
    - group: apps
      kind: ReplicaSet
    - group: rbac.authorization.k8s.io
      kind: ClusterRoles
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  assemblyPhase: "Pending"
  descriptor:
    type: "decks"
    version: {{.Values.tag}}
    description: >
      Dell EMC Common Kubernetes Services
    keywords:
      - "decks"
      - "srs"
      - "licensing"
    info:
      - "Copyright © 2019 Dell Inc. or its subsidiaries. All Rights Reserved."
{{- end}}
